version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html
  - source: /styles.css
    destination: /usr/share/nginx/html
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 30
      runas: root
